
export PATH="/Applications/Postgres.app/Contents/Versions/16/bin:${PATH}"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages:$PATH"

#Starship
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
eval "$(starship init zsh)"

# bun completions
[ -s "/Users/malinruwanpathirana/.bun/_bun" ] && source "/Users/malinruwanpathirana/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Added by Antigravity
export PATH="/Users/malinruwanpathirana/.antigravity/antigravity/bin:$PATH"

export COLORTERM=truecolor

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/malinruwanpathirana/.lmstudio/bin"
# End of LM Studio CLI section



# Added by Antigravity CLI installer
export PATH="/Users/malinruwanpathirana/.local/bin:$PATH"
export PATH="/Users/malinruwanpathirana/.local/bin:$PATH"

# kimi-code
export PATH="/Users/malinruwanpathirana/.kimi-code/bin:$PATH"
